settings:
  error messages: true
  
file types:
  - .zx
  - .zt
  - .ze
  - .virus
  - .bae
  - .dark
  - .baefell
  - .bya
  - .illuminati
  - .wrong
  - .zetox
  - .kevin
  - .js
  - .sk
  - .denizen
  - .lucky
  - .bowers
  - .lb